USE TF_1F_hugomelo;

DROP TABLE telefone;
DROP TABLE ITEM;
DROP TABLE COMPRA;
DROP TABLE PEDIDO;
DROP TABLE PRODUTO;
DROP TABLE CLIENTE;
DROP TABLE MARCA;
DROP TABLE TIPOPAGAMENTO;
DROP TABLE TIPOPRODUTO;